use serde::{Deserialize, Serialize};

use crate::chunk::{ChunkHeader, ChunkManifest, ChunkStatus};
use crate::error::{RecordingError, Result};
use crate::export::ExportChunk;

// ---------------------------------------------------------------------------
// IntegrityStatus
// ---------------------------------------------------------------------------

/// Integrity state of a recovered session.
///
/// Determined by triple verification:
/// - `Clean`: All three checks pass, full contiguity.
/// - `Partial`: Contiguous prefix recovered, some trailing chunks lost.
/// - `Incomplete`: First chunk missing or no usable prefix.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub(crate) enum IntegrityStatus {
    Clean,
    Partial,
    Incomplete,
}

impl IntegrityStatus {
    /// Return the human-readable label.
    pub(crate) fn as_label(&self) -> &'static str {
        match self {
            IntegrityStatus::Clean => "Clean",
            IntegrityStatus::Partial => "Partial",
            IntegrityStatus::Incomplete => "Incomplete",
        }
    }

    /// Return the CSS class suffix for this state.
    pub(crate) fn css_class(&self) -> &'static str {
        match self {
            IntegrityStatus::Clean => "integrity-clean",
            IntegrityStatus::Partial => "integrity-partial",
            IntegrityStatus::Incomplete => "integrity-incomplete",
        }
    }

    /// Return the recommended action string.
    pub(crate) fn recommended_action(&self) -> &'static str {
        match self {
            IntegrityStatus::Clean => "restore",
            IntegrityStatus::Partial => "partial",
            IntegrityStatus::Incomplete => "abandon",
        }
    }
}

// ---------------------------------------------------------------------------
// IntegrityReport
// ---------------------------------------------------------------------------

/// Comprehensive integrity report generated by triple verification.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct IntegrityReport {
    pub status: IntegrityStatus,
    pub total_chunks: u32,
    pub verified_chunks: u32,
    pub lost_chunks: u32,
    pub contiguous_prefix: u32,
    pub recommended_action: String,
    pub session_id: String,
    pub detail_message: Option<String>,
}

impl IntegrityReport {
    /// Generate a human-readable summary string.
    pub(crate) fn summary(&self) -> String {
        match self.status {
            IntegrityStatus::Clean => format!(
                "All {} chunks verified and contiguous.",
                self.verified_chunks
            ),
            IntegrityStatus::Partial => format!(
                "Clean — up to chunk {} of {}. {} chunks verified, {} lost.",
                self.contiguous_prefix,
                self.total_chunks,
                self.verified_chunks,
                self.lost_chunks,
            ),
            IntegrityStatus::Incomplete => {
                "This recording could not be fully recovered.".into()
            }
        }
    }

    /// Build the detail message for the integrity badge in the preview page.
    fn build_detail_message(status: &IntegrityStatus, contiguous: u32, total: u32) -> Option<String> {
        match status {
            IntegrityStatus::Clean => None,
            IntegrityStatus::Partial => Some(format!(
                "Clean — up to chunk {} of {}",
                contiguous, total,
            )),
            IntegrityStatus::Incomplete => {
                Some("This recording could not be fully recovered.".into())
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Verification results for each check
// ---------------------------------------------------------------------------

/// Result of a single chunk's manifest-vs-filesystem check.
#[derive(Debug, Clone, PartialEq)]
pub(crate) enum FileCheck {
    /// File exists with primary extension (.bin).
    Verified,
    /// File exists with secondary extension (.written) — lower confidence.
    WrittenOnly,
    /// File does not exist.
    Lost,
}

/// Result of a single chunk's size match check.
#[derive(Debug, Clone, PartialEq)]
pub(crate) enum SizeCheck {
    /// Actual file size matches expected size (header + payload).
    SizeOk,
    /// Size mismatch.
    SizeMismatch,
}

// ---------------------------------------------------------------------------
// SessionFile — represents a discovered file on OPFS
// ---------------------------------------------------------------------------

/// Represents a discovered session directory with its files.
#[derive(Debug, Clone)]
pub(crate) struct SessionDir {
    pub session_id: String,
    pub files: Vec<ChunkFileEntry>,
    pub manifest: Option<ChunkManifest>,
}

/// One chunk file discovered during OPFS scan.
#[derive(Debug, Clone)]
pub(crate) struct ChunkFileEntry {
    pub index: u32,
    pub extension: ChunkFileExt,
    pub actual_size: u64,
    pub raw_data: Vec<u8>,
}

/// Extension classification for chunk files from file naming.
#[derive(Debug, Clone, PartialEq)]
pub(crate) enum ChunkFileExt {
    Bin,
    Written,
    Partial,
}

// ---------------------------------------------------------------------------
// RecoveryManager
// ---------------------------------------------------------------------------

/// Manages crash recovery: OPFS scanning, triple verification, and restore.
pub(crate) struct RecoveryManager {
    /// Discovered orphan session directories.
    orphan_sessions: Vec<SessionDir>,
    /// Generated integrity report (set after restore).
    report: Option<IntegrityReport>,
}

impl RecoveryManager {
    /// Create a new RecoveryManager with no data.
    pub(crate) fn new() -> Self {
        Self {
            orphan_sessions: Vec::new(),
            report: None,
        }
    }

    /// Return the current integrity report, if any.
    pub(crate) fn report(&self) -> Option<&IntegrityReport> {
        self.report.as_ref()
    }

    /// Return the discovered orphan sessions.
    pub(crate) fn orphan_sessions(&self) -> &[SessionDir] {
        &self.orphan_sessions
    }

    /// Register discovered orphan sessions (called by OPFS scan).
    pub(crate) fn set_orphan_sessions(&mut self, sessions: Vec<SessionDir>) {
        self.orphan_sessions = sessions;
    }

    /// Clear all stored state.
    pub(crate) fn clear(&mut self) {
        self.orphan_sessions.clear();
        self.report = None;
    }
}

impl Default for RecoveryManager {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// Pure-logic operations — testable natively
// ---------------------------------------------------------------------------

/// Check the in_flight lock age.
///
/// Returns `true` if the lock is stale (>30s old), meaning the session is
/// considered crashed. Returns `false` if the lock is fresh or absent.
///
/// This is the pure-logic gate — callers provide the lock timestamp (or None).
pub(crate) fn is_lock_stale(lock_timestamp_ms: Option<f64>, now_ms: f64) -> bool {
    match lock_timestamp_ms {
        Some(ts) => {
            if ts.is_finite() && ts > 0.0 {
                if now_ms > ts {
                    (now_ms - ts) > 30_000.0
                } else {
                    // Lock is in the future or equal — not stale.
                    false
                }
            } else {
                // Invalid timestamp (NaN, negative) — treat as stale.
                true
            }
        }
        None => false, // No lock → no crash suspicion from lock.
    }
}

// ---------------------------------------------------------------------------
// Triple verification
// ---------------------------------------------------------------------------

/// Results of all three verification checks.
#[derive(Debug, Clone)]
pub(crate) struct TripleVerification {
    /// Per-chunk check 1 results (manifest vs filesystem).
    pub file_checks: Vec<(u32, FileCheck)>,
    /// Per-chunk check 2 results (size match), only for Verified entries.
    pub size_checks: Vec<(u32, SizeCheck)>,
    /// Check 3 result (index contiguity).
    pub contiguous_prefix: u32,
    /// Total chunks in the manifest.
    pub total_chunks: u32,
}

/// Run check 1: verify every committed/written manifest entry has a file.
pub(crate) fn check_manifest_vs_filesystem(
    manifest: &ChunkManifest,
    files: &[ChunkFileEntry],
) -> Vec<(u32, FileCheck)> {
    let mut results: Vec<(u32, FileCheck)> = Vec::new();

    for entry in &manifest.entries {
        // Only consider Written and Committed entries.
        if entry.status != ChunkStatus::Written && entry.status != ChunkStatus::Committed {
            continue;
        }

        let index = entry.chunk_index;
        let check = if files.iter().any(|f| f.index == index && f.extension == ChunkFileExt::Bin) {
            FileCheck::Verified
        } else if files.iter().any(|f| f.index == index && f.extension == ChunkFileExt::Written) {
            FileCheck::WrittenOnly
        } else {
            FileCheck::Lost
        };
        results.push((index, check));
    }

    results
}

/// Run check 2: verify file sizes match manifest entries.
///
/// Only checks entries that passed check 1 (Verified or WrittenOnly).
pub(crate) fn check_size_match(
    file_checks: &[(u32, FileCheck)],
    manifest: &ChunkManifest,
    files: &[ChunkFileEntry],
) -> Vec<(u32, SizeCheck)> {
    let mut results: Vec<(u32, SizeCheck)> = Vec::new();

    for (index, file_check) in file_checks {
        if *file_check == FileCheck::Lost {
            continue;
        }

        // Find the manifest entry.
        let manifest_entry = match manifest.entries.iter().find(|e| e.chunk_index == *index) {
            Some(e) => e,
            None => {
                results.push((*index, SizeCheck::SizeMismatch));
                continue;
            }
        };

        // Find the file entry.
        let file_entry = match files.iter().find(|f| f.index == *index) {
            Some(f) => f,
            None => {
                results.push((*index, SizeCheck::SizeMismatch));
                continue;
            }
        };

        // Expected size: 32-byte header + payload_size from manifest.
        let expected_size = 32u64 + manifest_entry.payload_size;
        let actual_size = file_entry.actual_size;

        if actual_size == expected_size {
            results.push((*index, SizeCheck::SizeOk));
        } else {
            results.push((*index, SizeCheck::SizeMismatch));
        }
    }

    results
}

/// Run check 3: identify the longest contiguous prefix from index 0.
pub(crate) fn check_index_contiguity(
    file_checks: &[(u32, FileCheck)],
    size_checks: &[(u32, SizeCheck)],
    total_chunks: u32,
) -> u32 {
    let mut contiguous = 0u32;

    for i in 0..total_chunks {
        // Check file existence (check 1).
        let file_ok = file_checks
            .iter()
            .any(|(idx, check)| *idx == i && *check != FileCheck::Lost);

        if !file_ok {
            break;
        }

        // Check size match (check 2).
        let size_ok = size_checks
            .iter()
            .any(|(idx, check)| *idx == i && *check == SizeCheck::SizeOk);

        if !size_ok {
            break;
        }

        contiguous += 1;
    }

    contiguous
}

/// Run all three verification checks and produce a `TripleVerification`.
pub(crate) fn triple_verify(
    manifest: &ChunkManifest,
    files: &[ChunkFileEntry],
) -> TripleVerification {
    let file_checks = check_manifest_vs_filesystem(manifest, files);
    let size_checks = check_size_match(&file_checks, manifest, files);
    let contiguous_prefix = check_index_contiguity(
        &file_checks,
        &size_checks,
        manifest.entries.len() as u32,
    );

    TripleVerification {
        file_checks,
        size_checks,
        contiguous_prefix,
        total_chunks: manifest.entries.len() as u32,
    }
}

/// Generate an `IntegrityReport` from triple verification results.
pub(crate) fn generate_report(
    session_id: &str,
    verification: &TripleVerification,
) -> IntegrityReport {
    let verified_chunks = verification
        .size_checks
        .iter()
        .filter(|(_, check)| *check == SizeCheck::SizeOk)
        .count() as u32;

    let lost_chunks = verification
        .file_checks
        .iter()
        .filter(|(_, check)| *check == FileCheck::Lost)
        .count() as u32;

    let (status, contiguous_prefix) = if verification.contiguous_prefix == 0 {
        (IntegrityStatus::Incomplete, 0)
    } else if verification.contiguous_prefix >= verification.total_chunks && lost_chunks == 0 {
        (IntegrityStatus::Clean, verification.total_chunks)
    } else {
        (IntegrityStatus::Partial, verification.contiguous_prefix)
    };

    let recommended_action = status.recommended_action().to_string();
    let detail_message = IntegrityReport::build_detail_message(
        &status,
        contiguous_prefix,
        verification.total_chunks,
    );

    // For Clean status, set total_chunks = verified_chunks (they're equal).
    // For Partial, use the actual total.
    // For Incomplete, all are lost.
    let (total, verified, lost) = match status {
        IntegrityStatus::Clean => (verified_chunks, verified_chunks, 0),
        IntegrityStatus::Partial => (verification.total_chunks, verified_chunks, lost_chunks),
        IntegrityStatus::Incomplete => (verification.total_chunks, 0, lost_chunks),
    };

    IntegrityReport {
        status,
        total_chunks: total,
        verified_chunks: verified,
        lost_chunks: lost,
        contiguous_prefix,
        recommended_action,
        session_id: session_id.to_string(),
        detail_message,
    }
}

/// Collect verified chunks for the export pipeline.
///
/// Returns the valid contiguous prefix chunks. If no chunks can be recovered,
/// returns `Err(RecordingError::EmptySession)`.
pub(crate) fn recover_contiguous_prefix(
    manifest: &ChunkManifest,
    files: &[ChunkFileEntry],
    contiguous_prefix: u32,
) -> Result<Vec<ExportChunk>> {
    if contiguous_prefix == 0 {
        return Err(RecordingError::EmptySession {
            details: "No usable chunks to recover from contiguous prefix".into(),
        });
    }

    let mut export_chunks: Vec<ExportChunk> = Vec::with_capacity(contiguous_prefix as usize);

    for i in 0..contiguous_prefix {
        // Check manifest entry exists for this index.
        if !manifest.entries.iter().any(|e| e.chunk_index == i) {
            return Err(RecordingError::ExportError {
                details: format!(
                    "Manifest entry missing for chunk index {} during recovery",
                    i,
                ),
            });
        }

        // Find the file entry — prefer .bin, fall back to .written.
        let file_entry = files
            .iter()
            .find(|f| f.index == i && f.extension == ChunkFileExt::Bin)
            .or_else(|| files.iter().find(|f| f.index == i && f.extension == ChunkFileExt::Written));

        let file_entry = match file_entry {
            Some(f) => f,
            None => {
                return Err(RecordingError::ExportError {
                    details: format!(
                        "File entry missing for chunk index {} during recovery",
                        i,
                    ),
                });
            }
        };

        // Parse the header from the raw data.
        let header_bytes: [u8; 32] = match file_entry.raw_data[..32].try_into() {
            Ok(b) => b,
            Err(_) => {
                return Err(RecordingError::ExportError {
                    details: format!(
                        "Chunk {}: insufficient data for header during recovery",
                        i,
                    ),
                });
            }
        };

        let header = ChunkHeader::decode(&header_bytes)?;

        // Extract payload (bytes after the 32-byte header).
        let payload = file_entry.raw_data[32..].to_vec();

        // Determine status: if .bin → Committed, if .written → Written.
        let status = if file_entry.extension == ChunkFileExt::Bin {
            ChunkStatus::Committed
        } else {
            ChunkStatus::Written
        };

        export_chunks.push(ExportChunk {
            index: i,
            header,
            payload,
            status,
        });
    }

    Ok(export_chunks)
}

// ---------------------------------------------------------------------------
// MockFileSystem — native-testable filesystem representation
// ---------------------------------------------------------------------------

/// A mock filesystem that simulates OPFS for native testing.
///
/// Stores session directories, chunk files, and manifests so all recovery
/// logic can be tested with `cargo test`.
#[derive(Debug, Clone)]
pub(crate) struct MockFileSystem {
    /// Discovered session directories.
    pub sessions: Vec<MockSessionDir>,
}

/// A single session directory in the mock filesystem.
#[derive(Debug, Clone)]
pub(crate) struct MockSessionDir {
    pub session_id: String,
    pub manifest: Option<ChunkManifest>,
    pub files: Vec<MockChunkFile>,
}

/// A chunk file in the mock filesystem.
#[derive(Debug, Clone)]
pub(crate) struct MockChunkFile {
    pub index: u32,
    pub extension: ChunkFileExt,
    /// Full content: 32-byte header + payload.
    pub data: Vec<u8>,
}

impl MockChunkFile {
    /// Create a new mock file with a valid header and payload.
    pub fn new(index: u32, extension: ChunkFileExt, payload: &[u8]) -> Self {
        let header = ChunkHeader::new(index, 0.0, payload);
        let header_bytes = header.encode();
        let mut data = Vec::with_capacity(32 + payload.len());
        data.extend_from_slice(&header_bytes);
        data.extend_from_slice(payload);
        Self {
            index,
            extension,
            data,
        }
    }

    /// Create a mock file with a corrupted checksum (for testing).
    pub fn new_corrupted(index: u32, extension: ChunkFileExt, payload: &[u8]) -> Self {
        let mut file = Self::new(index, extension, payload);
        // Corrupt one byte in the payload area (offset 32+).
        if file.data.len() > 33 {
            file.data[33] ^= 0xFF;
        }
        file
    }

    /// Return the actual size of this file on "disk".
    fn actual_size(&self) -> u64 {
        self.data.len() as u64
    }
}

impl MockFileSystem {
    /// Create a new empty mock filesystem.
    pub(crate) fn new() -> Self {
        Self {
            sessions: Vec::new(),
        }
    }

    /// Add a session directory.
    pub(crate) fn add_session(&mut self, session: MockSessionDir) {
        self.sessions.push(session);
    }

    /// Convert the mock filesystem to `SessionDir` entries for recovery.
    pub(crate) fn to_session_dirs(&self) -> Vec<SessionDir> {
        self.sessions
            .iter()
            .map(|s| {
                let files: Vec<ChunkFileEntry> = s
                    .files
                    .iter()
                    .map(|f| ChunkFileEntry {
                        index: f.index,
                        extension: f.extension.clone(),
                        actual_size: f.actual_size(),
                        raw_data: f.data.clone(),
                    })
                    .collect();

                SessionDir {
                    session_id: s.session_id.clone(),
                    files,
                    manifest: s.manifest.clone(),
                }
            })
            .collect()
    }
}

impl Default for MockFileSystem {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// Native unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    /// Create a mock session with `count` valid committed chunks.
    fn make_valid_session(session_id: &str, count: u32) -> MockSessionDir {
        let mut manifest = ChunkManifest::new(session_id.to_string());
        let mut files = Vec::new();

        for i in 0..count {
            let payload: Vec<u8> = vec![i as u8; 100];
            manifest.add_entry(crate::chunk::ManifestEntry {
                chunk_index: i,
                payload_size: 100,
                checksum: ChunkHeader::calc_checksum(&payload),
                status: crate::chunk::ChunkStatus::Committed,
                timestamp_ms: i as f64 * 1000.0,
            });
            files.push(MockChunkFile::new(i, ChunkFileExt::Bin, &payload));
        }

        MockSessionDir {
            session_id: session_id.to_string(),
            manifest: Some(manifest),
            files,
        }
    }

    /// Create a mock session with missing file at a given index.
    fn make_session_with_missing(session_id: &str, count: u32, missing_idx: u32) -> MockSessionDir {
        let mut manifest = ChunkManifest::new(session_id.to_string());
        let mut files = Vec::new();

        for i in 0..count {
            let payload: Vec<u8> = vec![i as u8; 100];
            manifest.add_entry(crate::chunk::ManifestEntry {
                chunk_index: i,
                payload_size: 100,
                checksum: ChunkHeader::calc_checksum(&payload),
                status: crate::chunk::ChunkStatus::Committed,
                timestamp_ms: i as f64 * 1000.0,
            });
            if i != missing_idx {
                files.push(MockChunkFile::new(i, ChunkFileExt::Bin, &payload));
            }
        }

        MockSessionDir {
            session_id: session_id.to_string(),
            manifest: Some(manifest),
            files,
        }
    }

    /// Create a mock session where chunk at `bad_size_idx` has wrong payload size.
    fn make_session_with_size_mismatch(
        session_id: &str,
        count: u32,
        bad_size_idx: u32,
    ) -> MockSessionDir {
        let mut manifest = ChunkManifest::new(session_id.to_string());
        let mut files = Vec::new();

        for i in 0..count {
            let payload: Vec<u8> = if i == bad_size_idx {
                vec![i as u8; 50] // smaller payload
            } else {
                vec![i as u8; 100]
            };
            manifest.add_entry(crate::chunk::ManifestEntry {
                chunk_index: i,
                payload_size: if i == bad_size_idx { 100 } else { 100 }, // manifest says 100
                checksum: ChunkHeader::calc_checksum(&payload),
                status: crate::chunk::ChunkStatus::Committed,
                timestamp_ms: i as f64 * 1000.0,
            });
            files.push(MockChunkFile::new(i, ChunkFileExt::Bin, &payload));
        }

        MockSessionDir {
            session_id: session_id.to_string(),
            manifest: Some(manifest),
            files,
        }
    }

    // -----------------------------------------------------------------------
    // IntegrityStatus tests
    // -----------------------------------------------------------------------

    #[test]
    fn test_initial_state() {
        let manager = RecoveryManager::new();
        assert!(manager.report().is_none());
        assert!(manager.orphan_sessions().is_empty());
    }

    // -----------------------------------------------------------------------
    // is_lock_stale tests
    // -----------------------------------------------------------------------

    #[test]
    fn test_in_flight_lock_check_fresh() {
        // Lock <30s old → treated as active.
        assert!(!is_lock_stale(Some(100_000.0), 105_000.0));   // 5s → fresh
        assert!(!is_lock_stale(Some(100_000.0), 129_999.0));   // ~30s → fresh
        assert!(!is_lock_stale(Some(100_000.0), 100_000.0));   // exact same → fresh
    }

    #[test]
    fn test_in_flight_lock_check_stale() {
        // Lock >30s old → treated as crashed.
        assert!(is_lock_stale(Some(100_000.0), 130_001.0));   // 30s+ → stale
        assert!(is_lock_stale(Some(100_000.0), 200_000.0));   // well past
    }

    #[test]
    fn test_in_flight_lock_absent() {
        // No lock → normal scan proceeds (not stale).
        assert!(!is_lock_stale(None, 100_000.0));
    }

    #[test]
    fn test_in_flight_lock_invalid_timestamp() {
        // Invalid timestamps (NaN, negative) → treat as stale.
        assert!(is_lock_stale(Some(f64::NAN), 100_000.0));
        assert!(is_lock_stale(Some(-1.0), 100_000.0));
    }

    // -----------------------------------------------------------------------
    // Triple verification — Check 1: Manifest vs Filesystem
    // -----------------------------------------------------------------------

    #[test]
    fn test_triple_verify_all_pass() {
        let session = make_valid_session("test-session", 5);
        let manifest = session.manifest.clone().unwrap();
        let fs = MockFileSystem { sessions: vec![session] };
        let session_dirs = fs.to_session_dirs();
        let files = &session_dirs[0].files;

        let verification = triple_verify(&manifest, files);

        assert_eq!(verification.total_chunks, 5);
        assert_eq!(verification.contiguous_prefix, 5);
        assert_eq!(
            verification.file_checks.iter().filter(|(_, c)| *c == FileCheck::Verified).count(),
            5,
        );
        assert_eq!(
            verification.size_checks.iter().filter(|(_, c)| *c == SizeCheck::SizeOk).count(),
            5,
        );
    }

    #[test]
    fn test_triple_verify_missing_file() {
        let session = make_session_with_missing("test-session", 5, 2);
        let manifest = session.manifest.clone().unwrap();
        let fs = MockFileSystem { sessions: vec![session] };
        let session_dirs = fs.to_session_dirs();
        let files = &session_dirs[0].files;

        let verification = triple_verify(&manifest, files);

        // Chunk 2 should be Lost.
        let lost = verification
            .file_checks
            .iter()
            .filter(|(idx, check)| *idx == 2 && *check == FileCheck::Lost)
            .count();
        assert_eq!(lost, 1, "chunk 2 should be lost");
        // Contiguous prefix breaks at 2 (0, 1 are ok, 2 is lost).
        assert_eq!(verification.contiguous_prefix, 2);
    }

    #[test]
    fn test_triple_verify_size_mismatch() {
        let session = make_session_with_size_mismatch("test-session", 5, 3);
        let manifest = session.manifest.clone().unwrap();
        let fs = MockFileSystem { sessions: vec![session] };
        let session_dirs = fs.to_session_dirs();
        let files = &session_dirs[0].files;

        let verification = triple_verify(&manifest, files);

        // Chunk 3 should have SizeMismatch.
        let mismatch = verification
            .size_checks
            .iter()
            .filter(|(idx, check)| *idx == 3 && *check == SizeCheck::SizeMismatch)
            .count();
        assert_eq!(mismatch, 1, "chunk 3 should have size mismatch");
        // Contiguous prefix: 0,1,2 pass, 3 fails → prefix = 3.
        assert_eq!(verification.contiguous_prefix, 3);
    }

    #[test]
    fn test_triple_verify_index_gap() {
        // Create a session where chunk 3 is missing entirely.
        let session = make_session_with_missing("test-session", 5, 3);
        let manifest = session.manifest.clone().unwrap();
        let fs = MockFileSystem { sessions: vec![session] };
        let session_dirs = fs.to_session_dirs();
        let files = &session_dirs[0].files;

        let verification = triple_verify(&manifest, files);

        // Contiguous prefix should be 3 (chunks 0,1,2 pass, 3 is lost).
        assert_eq!(verification.contiguous_prefix, 3);
    }

    #[test]
    fn test_triple_verify_all_lost() {
        let mut manifest = ChunkManifest::new("empty-session".to_string());
        manifest.add_entry(crate::chunk::ManifestEntry {
            chunk_index: 0,
            payload_size: 100,
            checksum: 0,
            status: crate::chunk::ChunkStatus::Committed,
            timestamp_ms: 0.0,
        });
        let files: Vec<ChunkFileEntry> = vec![];

        let verification = triple_verify(&manifest, &files);

        assert_eq!(verification.contiguous_prefix, 0);
        assert_eq!(
            verification.file_checks.iter().filter(|(_, c)| *c == FileCheck::Lost).count(),
            1,
        );
    }

    // -----------------------------------------------------------------------
    // IntegrityReport tests
    // -----------------------------------------------------------------------

    #[test]
    fn test_integrity_report_clean() {
        let session = make_valid_session("report-clean", 5);
        let manifest = session.manifest.clone().unwrap();
        let fs = MockFileSystem { sessions: vec![session] };
        let session_dirs = fs.to_session_dirs();
        let files = &session_dirs[0].files;

        let verification = triple_verify(&manifest, files);
        let report = generate_report("report-clean", &verification);

        assert_eq!(report.status, IntegrityStatus::Clean);
        assert_eq!(report.recommended_action, "restore");
        assert_eq!(report.total_chunks, 5);
        assert_eq!(report.verified_chunks, 5);
        assert_eq!(report.lost_chunks, 0);
        assert_eq!(report.contiguous_prefix, 5);
        assert!(report.detail_message.is_none());
    }

    #[test]
    fn test_integrity_report_partial() {
        let session = make_session_with_missing("report-partial", 5, 4);
        let manifest = session.manifest.clone().unwrap();
        let fs = MockFileSystem { sessions: vec![session] };
        let session_dirs = fs.to_session_dirs();
        let files = &session_dirs[0].files;

        let verification = triple_verify(&manifest, files);
        let report = generate_report("report-partial", &verification);

        assert_eq!(report.status, IntegrityStatus::Partial);
        assert_eq!(report.recommended_action, "partial");
        assert_eq!(report.contiguous_prefix, 4);
        assert_eq!(report.total_chunks, 5);
        assert!(report.detail_message.is_some());
        assert!(
            report.detail_message.as_ref().unwrap().contains("up to chunk"),
            "Partial detail should mention chunk range",
        );
    }

    #[test]
    fn test_integrity_report_incomplete() {
        let mut manifest = ChunkManifest::new("report-incomplete".to_string());
        manifest.add_entry(crate::chunk::ManifestEntry {
            chunk_index: 0,
            payload_size: 100,
            checksum: 0,
            status: crate::chunk::ChunkStatus::Committed,
            timestamp_ms: 0.0,
        });
        let files: Vec<ChunkFileEntry> = vec![];

        let verification = triple_verify(&manifest, &files);
        let report = generate_report("report-incomplete", &verification);

        assert_eq!(report.status, IntegrityStatus::Incomplete);
        assert_eq!(report.recommended_action, "abandon");
        assert_eq!(report.contiguous_prefix, 0);
        assert_eq!(report.verified_chunks, 0);
        assert!(report.detail_message.is_some());
        assert!(
            report.detail_message.as_ref().unwrap().contains("could not be fully recovered"),
            "Incomplete detail should explain unrecoverable state",
        );
    }

    #[test]
    fn test_integrity_report_summary() {
        // Clean.
        let session = make_valid_session("summary", 3);
        let manifest = session.manifest.clone().unwrap();
        let fs = MockFileSystem { sessions: vec![session] };
        let session_dirs = fs.to_session_dirs();
        let files = &session_dirs[0].files;
        let verification = triple_verify(&manifest, files);
        let report = generate_report("summary", &verification);
        assert!(report.summary().contains("verif"), "Clean summary mentions verification");

        // Partial.
        let session2 = make_session_with_missing("summary-partial", 5, 4);
        let manifest2 = session2.manifest.clone().unwrap();
        let fs2 = MockFileSystem { sessions: vec![session2] };
        let dirs2 = fs2.to_session_dirs();
        let files2 = &dirs2[0].files;
        let verification2 = triple_verify(&manifest2, files2);
        let report2 = generate_report("summary-partial", &verification2);
        assert!(report2.summary().contains("Clean — up to chunk"), "Partial summary mentions range");

        // Incomplete.
        let report3 = IntegrityReport {
            status: IntegrityStatus::Incomplete,
            total_chunks: 5,
            verified_chunks: 0,
            lost_chunks: 5,
            contiguous_prefix: 0,
            recommended_action: "abandon".into(),
            session_id: "summary-incomplete".into(),
            detail_message: Some("This recording could not be fully recovered.".into()),
        };
        assert!(
            report3.summary().contains("could not be fully recovered"),
            "Incomplete summary mentions unrecoverable state",
        );
    }

    #[test]
    fn test_integrity_status_as_label() {
        assert_eq!(IntegrityStatus::Clean.as_label(), "Clean");
        assert_eq!(IntegrityStatus::Partial.as_label(), "Partial");
        assert_eq!(IntegrityStatus::Incomplete.as_label(), "Incomplete");
    }

    #[test]
    fn test_integrity_status_css_class() {
        assert_eq!(IntegrityStatus::Clean.css_class(), "integrity-clean");
        assert_eq!(IntegrityStatus::Partial.css_class(), "integrity-partial");
        assert_eq!(IntegrityStatus::Incomplete.css_class(), "integrity-incomplete");
    }

    #[test]
    fn test_integrity_status_recommended_action() {
        assert_eq!(IntegrityStatus::Clean.recommended_action(), "restore");
        assert_eq!(IntegrityStatus::Partial.recommended_action(), "partial");
        assert_eq!(IntegrityStatus::Incomplete.recommended_action(), "abandon");
    }

    // -----------------------------------------------------------------------
    // recover_contiguous_prefix
    // -----------------------------------------------------------------------

    #[test]
    fn test_recovery_contiguous_prefix_collection() {
        let session = make_valid_session("prefix-test", 3);
        let manifest = session.manifest.clone().unwrap();
        let fs = MockFileSystem { sessions: vec![session] };
        let session_dirs = fs.to_session_dirs();
        let files = &session_dirs[0].files;

        let verification = triple_verify(&manifest, files);
        let result = recover_contiguous_prefix(&manifest, files, verification.contiguous_prefix);

        assert!(result.is_ok(), "recover_contiguous_prefix should succeed");
        let chunks = result.unwrap();
        assert_eq!(chunks.len(), 3, "should recover 3 chunks");
        // Verify indices.
        for (i, chunk) in chunks.iter().enumerate() {
            assert_eq!(chunk.index, i as u32);
        }
    }

    #[test]
    fn test_recovery_export_empty() {
        let manifest = ChunkManifest::new("empty-test".to_string());
        let files: Vec<ChunkFileEntry> = vec![];

        let result = recover_contiguous_prefix(&manifest, &files, 0);
        assert!(result.is_err(), "empty recovery should return Err");
    }

    // -----------------------------------------------------------------------
    // RecoveryManager lifecycle
    // -----------------------------------------------------------------------

    #[test]
    fn test_recovery_manager_default() {
        let manager = RecoveryManager::default();
        assert!(manager.orphan_sessions().is_empty());
        assert!(manager.report().is_none());
    }

    #[test]
    fn test_recovery_manager_clear() {
        let mut manager = RecoveryManager::new();
        let session = make_valid_session("test", 1);
        let fs = MockFileSystem { sessions: vec![session] };
        manager.set_orphan_sessions(fs.to_session_dirs());
        assert_eq!(manager.orphan_sessions().len(), 1);

        manager.clear();
        assert!(manager.orphan_sessions().is_empty());
        assert!(manager.report().is_none());
    }

    // -----------------------------------------------------------------------
    // check_manifest_vs_filesystem — edge cases
    // -----------------------------------------------------------------------

    #[test]
    fn test_check_manifest_vs_filesystem_partial_entries_skipped() {
        let mut manifest = ChunkManifest::new("test".to_string());
        manifest.add_entry(crate::chunk::ManifestEntry {
            chunk_index: 0,
            payload_size: 10,
            checksum: 0,
            status: crate::chunk::ChunkStatus::Partial,
            timestamp_ms: 0.0,
        });
        manifest.add_entry(crate::chunk::ManifestEntry {
            chunk_index: 1,
            payload_size: 10,
            checksum: 0,
            status: crate::chunk::ChunkStatus::Written,
            timestamp_ms: 0.0,
        });

        let files = vec![
            ChunkFileEntry {
                index: 0,
                extension: ChunkFileExt::Partial,
                actual_size: 42,
                raw_data: vec![],
            },
            ChunkFileEntry {
                index: 1,
                extension: ChunkFileExt::Written,
                actual_size: 42,
                raw_data: vec![],
            },
        ];

        let results = check_manifest_vs_filesystem(&manifest, &files);

        // Only Written/Committed entries should be checked.
        // Entry 0 (Partial) is skipped; entry 1 (Written) should be WrittenOnly or Verified.
        assert_eq!(results.len(), 1, "only Written entries should be checked");
        assert_eq!(results[0].0, 1, "entry 1 should be checked");
        assert_eq!(results[0].1, FileCheck::WrittenOnly, "should find Written file");
    }

    #[test]
    fn test_check_manifest_vs_filesystem_prefers_bin() {
        let mut manifest = ChunkManifest::new("test".to_string());
        manifest.add_entry(crate::chunk::ManifestEntry {
            chunk_index: 0,
            payload_size: 10,
            checksum: 0,
            status: crate::chunk::ChunkStatus::Committed,
            timestamp_ms: 0.0,
        });

        // Both .bin and .written exist — should prefer .bin (Verified).
        let files = vec![
            ChunkFileEntry {
                index: 0,
                extension: ChunkFileExt::Written,
                actual_size: 42,
                raw_data: vec![],
            },
            ChunkFileEntry {
                index: 0,
                extension: ChunkFileExt::Bin,
                actual_size: 42,
                raw_data: vec![],
            },
        ];

        let results = check_manifest_vs_filesystem(&manifest, &files);
        assert_eq!(results[0].1, FileCheck::Verified, "should prefer .bin → Verified");
    }

    // -----------------------------------------------------------------------
    // check_index_contiguity — edge cases
    // -----------------------------------------------------------------------

    #[test]
    fn test_check_index_contiguity_mid_sequence_gap() {
        let manifest_count = 5u32;
        let file_checks = vec![
            (0, FileCheck::Verified),
            (1, FileCheck::Verified),
            (2, FileCheck::Lost),
            (3, FileCheck::Verified),
            (4, FileCheck::Verified),
        ];
        let size_checks = vec![
            (0, SizeCheck::SizeOk),
            (1, SizeCheck::SizeOk),
            // index 2 is lost, so no size check.
            (3, SizeCheck::SizeOk),
            (4, SizeCheck::SizeOk),
        ];

        let prefix = check_index_contiguity(&file_checks, &size_checks, manifest_count);
        // First gap at index 2, so prefix = 2.
        assert_eq!(prefix, 2);
    }

    #[test]
    fn test_check_index_contiguity_all_good() {
        let file_checks = vec![
            (0, FileCheck::Verified),
            (1, FileCheck::Verified),
            (2, FileCheck::Verified),
        ];
        let size_checks = vec![
            (0, SizeCheck::SizeOk),
            (1, SizeCheck::SizeOk),
            (2, SizeCheck::SizeOk),
        ];

        let prefix = check_index_contiguity(&file_checks, &size_checks, 3);
        assert_eq!(prefix, 3);
    }

    #[test]
    fn test_check_index_contiguity_first_chunk_lost() {
        let file_checks = vec![
            (0, FileCheck::Lost),
            (1, FileCheck::Verified),
            (2, FileCheck::Verified),
        ];
        let size_checks = vec![
            // index 0 is lost.
            (1, SizeCheck::SizeOk),
            (2, SizeCheck::SizeOk),
        ];

        let prefix = check_index_contiguity(&file_checks, &size_checks, 3);
        assert_eq!(prefix, 0, "first chunk lost → no contiguous prefix");
    }

    // -----------------------------------------------------------------------
    // check_size_match — edge cases
    // -----------------------------------------------------------------------

    #[test]
    fn test_check_size_match_lost_skipped() {
        let file_checks = vec![(0, FileCheck::Lost)];
        let manifest = ChunkManifest::new("test".to_string());
        let files: Vec<ChunkFileEntry> = vec![];

        let results = check_size_match(&file_checks, &manifest, &files);
        assert!(results.is_empty(), "Lost entries should not be size-checked");
    }

    // -----------------------------------------------------------------------
    // Deferred items from Story 1.7
    // -----------------------------------------------------------------------

    #[test]
    fn test_recovery_deferred_partial_detail() {
        let report = IntegrityReport {
            status: IntegrityStatus::Partial,
            total_chunks: 10,
            verified_chunks: 7,
            lost_chunks: 3,
            contiguous_prefix: 7,
            recommended_action: "partial".into(),
            session_id: "deferred-partial".into(),
            detail_message: Some("Clean — up to chunk 7 of 10".into()),
        };

        assert_eq!(
            report.detail_message.as_ref().unwrap(),
            "Clean — up to chunk 7 of 10",
        );
        assert!(report.summary().contains("Clean — up to chunk"));
    }

    #[test]
    fn test_recovery_deferred_incomplete_message() {
        let report = IntegrityReport {
            status: IntegrityStatus::Incomplete,
            total_chunks: 5,
            verified_chunks: 0,
            lost_chunks: 5,
            contiguous_prefix: 0,
            recommended_action: "abandon".into(),
            session_id: "deferred-incomplete".into(),
            detail_message: Some("This recording could not be fully recovered.".into()),
        };

        assert_eq!(
            report.detail_message.as_ref().unwrap(),
            "This recording could not be fully recovered.",
        );
        assert!(report.summary().contains("could not be fully recovered"));
    }
}
